=== Soy9461/NavigationB/VisibleNav/lib/aracschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:element name="arac">
<xsd:complexType>
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:element name="edgemappingset" type="EdgeMappingSet" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element name="force" type="Force" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element name="tree" type="Tree" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element name="flow" type="Flow" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element name="grid" type="Grid" minOccurs="0" maxOccurs="unbounded" />
  </xsd:sequence>
</xsd:complexType>
</xsd:element>

<xsd:complexType name="EdgeMappingSet">
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:element name="edgemapping" type="EdgeMapping" minOccurs="0" maxOccurs="unbounded" />
  </xsd:sequence>
  <xsd:attribute name="name" type="xsd:string" use="required"/>
</xsd:complexType>
<xsd:complexType name="EdgeMappingSetRef">
  <xsd:attribute name="name" type="xsd:string" use="required"/>
</xsd:complexType>

<xsd:complexType name="NL">
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:element name="edgemapping" type="EdgeMapping" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element name="edgemappingset" type="EdgeMappingSetRef" minOccurs="0" maxOccurs="unbounded" />
  </xsd:sequence>
  <xsd:attribute name="name" use="required">
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:pattern value="[a-zA-Z0-9]([a-zA-Z0-9\-_#.])+"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:attribute>
  <xsd:attribute name="layoutOrigin" type="layoutOrigin" use="optional"/>
  <xsd:attribute name="layoutOriginAnchor" type="layoutOriginAnchor" use="optional"/>
  <xsd:attribute name="edgeType" type="EdgeType" use="optional"/>
  <xsd:attribute name="edgeTypeDesc" type="xsd:string" use="optional"/>
  <xsd:attribute name="forceEdgeType" type="xsd:boolean" use="optional"/>
  <xsd:attribute name="tags" type="xsd:string" use="optional"/>
</xsd:complexType>

<xsd:complexType name="EdgeMapping">
  <xsd:sequence>
    <xsd:element name="propval" type="PropVal" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element name="config" type="EdgeMappingConfig" minOccurs="1" maxOccurs="1" />
    <xsd:element name="alternatives" minOccurs="0" maxOccurs="1">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="config" type="EdgeMappingConfig" minOccurs="1" maxOccurs="unbounded" />
      </xsd:sequence>
    </xsd:complexType>
    </xsd:element>
  </xsd:sequence>
</xsd:complexType>
<xsd:complexType name="PropVal">
  <xsd:attribute name="prop" type="xsd:string" use="required"/>
  <xsd:attribute name="value" type="xsd:string" use="required"/>
</xsd:complexType>
<xsd:complexType name="EdgeMappingConfig">
  <!-- TODO: fix to bbox position --><xsd:attribute name="srcPortPos" type="xsd:string" use="required"/>
  <!-- TODO: fix to bbox position --><xsd:attribute name="tgtPortPos" type="xsd:string" use="required"/>
  <xsd:attribute name="edgeType" type="EdgeType" use="optional"/>
</xsd:complexType>

<xsd:complexType name="NLDistanceBased">
  <xsd:complexContent>
  <xsd:extension base="NL">
    <xsd:attribute name="nodeDistance" type="xsd:nonNegativeInteger" use="optional"/>
  </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>
<xsd:complexType name="TDistanceBased">
  <xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:element name="edgemapping" type="EdgeMapping" minOccurs="0" maxOccurs="unbounded" />
    <xsd:element name="edgemappingset" type="EdgeMappingSetRef" minOccurs="0" maxOccurs="unbounded" />
  </xsd:sequence>
  <xsd:attribute name="nodeDistance" type="xsd:nonNegativeInteger" use="optional"/>
  <xsd:attribute name="edgeType" type="EdgeType" use="optional"/>
  <xsd:attribute name="edgeTypeDesc" type="xsd:string" use="optional"/>
  <xsd:attribute name="forceEdgeType" type="xsd:boolean" use="optional"/>
</xsd:complexType>

<xsd:complexType name="NLHVOrientationBased">
  <xsd:complexContent>
  <xsd:extension base="NLDistanceBased">
    <xsd:attribute name="layoutOrientation" type="layoutOrientation" use="optional"/>
  </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>
<xsd:complexType name="THVOrientationBased">
  <xsd:complexContent>
  <xsd:extension base="TDistanceBased">
    <xsd:attribute name="layoutOrientation" type="layoutOrientation" use="optional"/>
  </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="NLHVLayerBased">
  <xsd:complexContent>
  <xsd:extension base="NLHVOrientationBased">
    <xsd:attribute name="layerDistance" type="xsd:nonNegativeInteger" use="optional"/>
  </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>
<xsd:complexType name="THVLayerBased">
  <xsd:complexContent>
  <xsd:extension base="THVOrientationBased">
    <xsd:attribute name="layerDistance" type="xsd:nonNegativeInteger" use="optional"/>
  </xsd:extension>
  </xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="Force">
  <xsd:complexContent>
  <xsd:extension base="NLDistanceBased">
    <xsd:attribute name="attraction" type="xsd:float" use="optional" />
    <xsd:attribute name="rejection" type="xsd:float" use="optional" />
    <xsd:attribute name="gravitation" type="xsd:float" use="optional" />
    <xsd:attribute name="iterations" type="xsd:positiveInteger" use="optional" />
 </xsd:extension>
 </xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="Tree">
  <xsd:complexContent>
  <xsd:extension base="NLHVLayerBased">
    <xsd:sequence minOccurs="0" maxOccurs="unbounded">
      <xsd:element name="treelevel" type="TreeLevel" minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="treeStyle" type="TreeStyle" use="optional"/>
    <xsd:attribute name="parentBalancing" type="ParentBalancing" use="optional"/>
 </xsd:extension>
 </xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="TreeLevel">
  <xsd:complexContent>
  <xsd:extension base="THVLayerBased">
    <xsd:attribute name="level" type="xsd:positiveInteger" use="required"/>
    <xsd:attribute name="treeStyle" type="TreeStyle" use="optional"/>
    <xsd:attribute name="parentBalancing" type="ParentBalancing" use="optional"/>
 </xsd:extension>
 </xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="Flow">
  <xsd:complexContent>
  <xsd:extension base="NLHVLayerBased">
    <xsd:attribute name="pathBalancing" type="PathBalancing" use="optional"/>
 </xsd:extension>
 </xsd:complexContent>
</xsd:complexType>

<xsd:complexType name="Grid">
  <xsd:complexContent>
  <xsd:extension base="NL">
    <xsd:attribute name="type" type="GridType" use="optional"/>
    <xsd:attribute name="direction" type="FlowDirection" use="optional"/>
    <xsd:attribute name="cellCount" type="xsd:positiveInteger" use="optional"/>
    <xsd:attribute name="cellExtend" type="xsd:nonNegativeInteger" use="optional"/>
    <xsd:attribute name="cellWidth" type="xsd:nonNegativeInteger" use="optional"/>
    <xsd:attribute name="cellHeight" type="xsd:nonNegativeInteger" use="optional"/>
    <xsd:attribute name="colGap" type="xsd:integer" use="optional"/>
    <xsd:attribute name="rowGap" type="xsd:integer" use="optional"/>
    <xsd:attribute name="xAscending" type="xsd:boolean" use="optional"/>
    <xsd:attribute name="yAscending" type="xsd:boolean" use="optional"/>
    <xsd:attribute name="xArea" type="xsd:nonNegativeInteger" use="optional"/>
    <xsd:attribute name="yArea" type="xsd:nonNegativeInteger" use="optional"/>
 </xsd:extension>
 </xsd:complexContent>
</xsd:complexType>

<xsd:simpleType name="layoutOrigin">
  <xsd:restriction base="xsd:string">
    <xsd:pattern value="[0-9]*[,][ ]*[0-9]*"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="layoutOriginAnchor">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="Center"/>
    <xsd:enumeration value="LeftTop"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="layoutOrientation">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="TopToBottom"/>
    <xsd:enumeration value="BottomToTop"/>
    <xsd:enumeration value="LeftToRight"/>
    <xsd:enumeration value="RightToLeft"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="ParentBalancing">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="Head"/>
    <xsd:enumeration value="Median"/>
    <xsd:enumeration value="Tail"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="PathBalancing">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="Normal"/>
    <xsd:enumeration value="LongestPath"/>
    <xsd:enumeration value="ShortestPath"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="TreeStyle">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="TreeNormal"/>
    <xsd:enumeration value="TreeListSingle"/>
    <xsd:enumeration value="TreeListDouble"/>
    <xsd:enumeration value="TreeHV"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="GridType">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="GridFlowDistance"/>
    <xsd:enumeration value="GridFlowRaster"/>
    <xsd:enumeration value="GridFlowGridback"/>
    <xsd:enumeration value="GridRaster"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="FlowDirection">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="RowFlow"/>
    <xsd:enumeration value="ColFlow"/>
  </xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="EdgeType">
  <xsd:restriction base="xsd:string">
    <xsd:enumeration value="Straight"/>
    <xsd:enumeration value="Elbow"/>
    <xsd:enumeration value="Orthogonal"/>
  </xsd:restriction>
</xsd:simpleType>

</xsd:schema>

=== Soy9461/NavigationB/VisibleNav/lib/aracconfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<arac xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="aracschema.xsd">

  <force name="Force-CenterPoints" layoutOtrigin="2000,2000" nodeDistance="3200" iterations="120">
    <edgemappingset name="CenterPoints" />
  </force>
  <force name="Force-CenterPoints-Anim" layoutOtrigin="2000,2000" nodeDistance="2000" iterations="1">
    <edgemappingset name="CenterPoints" />
  </force>

  <flow name="Flow-CardinalPoints" layoutOrigin="2000,2000" nodeDistance="1000" layerDistance="1500" >
    <edgemappingset name="Flow-CardinalPoints" />
  </flow>
  <flow name="Flow-CardinalPoints-Orth" layoutOrigin="2000,2000" nodeDistance="1000" layerDistance="1500"
        edgeType="Orthogonal" >
    <edgemappingset name="Flow-CardinalPoints" />
  </flow>

  <flow name="Flow-TTB-N" layoutOrigin="2000,2000" layoutOrientation="TopToBottom" nodeDistance="1000" layerDistance="1500"
        edgeType="Orthogonal" >
    <edgemappingset name="Flow-CardinalPoints" />
  </flow>
  <flow name="Flow-BTT-N" layoutOrigin="2000,2000" layoutOrientation="BottomToTop" nodeDistance="1000" layerDistance="1500"
        edgeType="Orthogonal" >
    <edgemappingset name="Flow-CardinalPoints" />
  </flow>
  <flow name="Flow-LTR-N" layoutOrigin="2000,2000" layoutOrientation="LeftToRight" nodeDistance="1000" layerDistance="1500"
        edgeType="Orthogonal" >
    <edgemappingset name="Flow-CardinalPoints" />
  </flow>
  <flow name="Flow-RTL-N" layoutOrigin="2000,2000" layoutOrientation="RightToLeft" nodeDistance="1000" layerDistance="1500"
        edgeType="Orthogonal" >
    <edgemappingset name="Flow-CardinalPoints" />
  </flow>

  <flow name="Flow-TTB-LP" layoutOrigin="2000,2000" layoutOrientation="TopToBottom" nodeDistance="1000" layerDistance="1500" pathBalancing="LongestPath"
        edgeType="Orthogonal" >
    <edgemappingset name="Flow-CardinalPoints" />
  </flow>
  <flow name="Flow-BTT-LP" layoutOrigin="2000,2000" layoutOrientation="BottomToTop" nodeDistance="1000" layerDistance="1500" pathBalancing="LongestPath"
        edgeType="Orthogonal" >
    <edgemappingset name="Flow-CardinalPoints" />
  </flow>
  <flow name="Flow-LTR-LP" layoutOrigin="2000,2000" layoutOrientation="LeftToRight" nodeDistance="1000" layerDistance="1500" pathBalancing="LongestPath"
        edgeType="Orthogonal" >
    <edgemappingset name="Flow-CardinalPoints" />
  </flow>
  <flow name="Flow-RTL-LP" layoutOrigin="2000,2000" layoutOrientation="RightToLeft" nodeDistance="1000" layerDistance="1500" pathBalancing="LongestPath"
        edgeType="Orthogonal" >
    <edgemappingset name="Flow-CardinalPoints" />
  </flow>

  <tree name="Tree-Default" layoutOrigin="2000,2000" />
  <tree name="Tree-CardinalPoints" layoutOrigin="2000,2000" nodeDistance="500" layerDistance="1000" >
    <edgemappingset name="TreeN-CardinalPoints" />
    <edgemappingset name="TreeLS-CardinalPoints" />
    <edgemappingset name="TreeLD-CardinalPoints" />
    <edgemappingset name="TreeHV-CardinalPoints" />
  </tree>
  <tree name="Tree-CardinalPoints-Orth" layoutOrigin="2000,2000" nodeDistance="500" layerDistance="1000"
        edgeType="Orthogonal" >
    <edgemappingset name="TreeN-CardinalPoints" />
    <edgemappingset name="TreeLS-CardinalPoints" />
    <edgemappingset name="TreeLD-CardinalPoints" />
    <edgemappingset name="TreeHV-CardinalPoints" />
  </tree>

  <chain name="OrgChart-Demo" configs="OrgChart-Demo2,OrgChart-Demo1" />
  <tree name="OrgChart-Demo1" layoutOrigin="2000,2000" layoutOrientation="TopToBottom" treeStyle="TreeNormal" nodeDistance="500" layerDistance="1000"
        edgeType="Orthogonal" edgeTypeDesc="lineCorners:200" tags="orgmanager, orgperson" careAnnex="true" >
    <edgemappingset name="TreeN-CardinalPoints" />
	<!-- treelevel level="4" layoutOrientation="TopToBottom" treeStyle="TreeListSingle" nodeDistance="500" layerDistance="-1000"
               edgeType="Elbow" edgeTypeDesc="elbow:Target" tags="orgmanager, orgperson" >
      <edgemappingset name="TreeLS-CardinalPoints" />
	</treelevel -->
	<node tag="orgmanager" layoutOrientation="TopToBottom" treeStyle="TreeNormal" nodeDistance="500" layerDistance="1000"
          edgeType="Orthogonal" edgeTypeDesc="lineCorners:200" tags="orgmanager, orgperson" careAnnex="true" >
      <edgemappingset name="TreeN-CardinalPoints" />
	</node>
	<node tag="orgperson" layoutOrientation="TopToBottom" treeStyle="TreeListSingle" nodeDistance="500" layerDistance="-1000"
          edgeType="Elbow" edgeTypeDesc="elbow:Target; lineCorners:200" tags="orgperson, orgmanager" careAnnex="true" tagsNonAnnex="orgmanager" >
      <edgemappingset name="TreeLS-CardinalPoints" />
	</node>
  </tree>
  <tree name="OrgChart-Demo2" treeStyle="TreeNormal" layoutOrigin="2000,2000" layoutOrientation="TopToBottom" nodeDistance="500" layerDistance="-500"
        tags="orgmanager, orgperson, orgassistent" careAnnex="true" tagsNonAnnex="orgmanager, orgperson" >
    <edgemappingset name="TreeN-CardinalPoints" />
	<node tag="orgmanager" subsequent="false" layoutOrientation="TopToBottom" treeStyle="TreeListDouble" nodeDistance="500" layerDistance="-500"
          edgeType="Elbow" edgeTypeDesc="elbow:Target; lineCorners:200" tags="orgmanager, orgassistent" careAnnex="true" tagsNonAnnex="orgperson, orgmanager" >
      <edgemappingset name="TreeLD-CardinalPoints" />
	</node>
	<node tag="orgperson" subsequent="false" layoutOrientation="TopToBottom" treeStyle="TreeListDouble" nodeDistance="500" layerDistance="-500"
          edgeType="Elbow" edgeTypeDesc="elbow:Target; lineCorners:200" tags="orgperson, orgassistent" careAnnex="true" tagsNonAnnex="orgperson, orgmanager" >
      <edgemappingset name="TreeLD-CardinalPoints" />
	</node>
  </tree>
  <!-- tree name="OrgChart-Demo3" treeStyle="TreeNormal" layoutOrigin="2000,2000" layoutOrientation="TopToBottom" nodeDistance="1000" layerDistance="-500"
        tags="orgmanager, orgperson, orgservant" careAnnex="true" tagsNonAnnex="orgmanager, orgperson, orgassistent" >
    <edgemappingset name="TreeN-CardinalPoints" />
	<node tag="orgmanager" subsequent="false" layoutOrientation="RightToLeft" treeStyle="TreeListDouble" nodeDistance="1000" layerDistance="-500"
          edgeType="Elbow" edgeTypeDesc="elbow:Target; srcSlope:500" tags="orgmanager, orgservant" careAnnex="true" tagsNonAnnex="orgperson, orgassistent" >
      <edgemappingset name="TreeLD-CardinalPoints" />
	</node>
	<node tag="orgperson" subsequent="false" layoutOrientation="RightToLeft" treeStyle="TreeListDouble" nodeDistance="1000" layerDistance="-500"
          edgeType="Elbow" edgeTypeDesc="elbow:Target; srcSlope:500" tags="orgperson, orgservant" careAnnex="true" tagsNonAnnex="orgmanager, orgassistent" >
      <edgemappingset name="TreeLD-CardinalPoints" />
	</node>
  </tree -->

  <tree name="Tree-Lo.TB" layoutOrigin="2000,2000" layoutOrientation="TopToBottom" nodeDistance="500" layerDistance="1000" >
    <edgemappingset name="TreeN-CardinalPoints" />
  </tree>
  <tree name="Tree-Lo.BT" layoutOrigin="2000,2000" layoutOrientation="BottomToTop" nodeDistance="500" layerDistance="1000" >
    <edgemappingset name="TreeN-CardinalPoints" />
  </tree>
  <tree name="Tree-Lo.LR" layoutOrigin="2000,2000" layoutOrientation="LeftToRight" nodeDistance="500" layerDistance="1000" >
    <edgemappingset name="TreeN-CardinalPoints" />
  </tree>
  <tree name="Tree-Lo.RL" layoutOrigin="2000,2000" layoutOrientation="RightToLeft" nodeDistance="500" layerDistance="1000" >
    <edgemappingset name="TreeN-CardinalPoints" />
  </tree>

  <tree name="Tree-Lo.TB-Pb.H" layoutOrigin="2000,2000" layoutOrientation="TopToBottom" parentBalancing="Head" nodeDistance="500" layerDistance="1000" >
    <edgemappingset name="TreeN-CardinalPoints" />
  </tree>
  <tree name="Tree-Lo.BT-Pb.H" layoutOrigin="2000,2000" layoutOrientation="BottomToTop" parentBalancing="Head" nodeDistance="500" layerDistance="1000" >
    <edgemappingset name="TreeN-CardinalPoints" />
  </tree>
  <tree name="Tree-Lo.LR-Pb.H" layoutOrigin="2000,2000" layoutOrientation="LeftToRight" parentBalancing="Head" nodeDistance="500" layerDistance="1000" >
    <edgemappingset name="TreeN-CardinalPoints" />
  </tree>
  <tree name="Tree-Lo.RL-Pb.H" layoutOrigin="2000,2000" layoutOrientation="RightToLeft" parentBalancing="Head" nodeDistance="500" layerDistance="1000" >
    <edgemappingset name="TreeN-CardinalPoints" />
  </tree>

  <tree name="Tree-Lo.TB-Pb.T" layoutOrigin="2000,2000" layoutOrientation="TopToBottom" parentBalancing="Tail" nodeDistance="500" layerDistance="1000" >
    <edgemappingset name="TreeN-CardinalPoints" />
  </tree>
  <tree name="Tree-Lo.BT-Pb.T" layoutOrigin="2000,2000" layoutOrientation="BottomToTop" parentBalancing="Tail" nodeDistance="500" layerDistance="1000" >
    <edgemappingset name="TreeN-CardinalPoints" />
  </tree>
  <tree name="Tree-Lo.LR-Pb.T" layoutOrigin="2000,2000" layoutOrientation="LeftToRight" parentBalancing="Tail" nodeDistance="500" layerDistance="1000" >
    <edgemappingset name="TreeN-CardinalPoints" />
  </tree>
  <tree name="Tree-Lo.RL-Pb.T" layoutOrigin="2000,2000" layoutOrientation="RightToLeft" parentBalancing="Tail" nodeDistance="500" layerDistance="1000" >
    <edgemappingset name="TreeN-CardinalPoints" />
  </tree>

  <tree name="ListS-Lo.TB-Pb.HM" treeStyle="TreeListSingle" layoutOrigin="2000,2000" layoutOrientation="TopToBottom" nodeDistance="1000" layerDistance="0"
        edgeType="Elbow" edgeTypeDesc="elbow:Target" >
    <edgemappingset name="TreeLS-CardinalPoints" />
  </tree>
  <tree name="ListS-Lo.BT-Pb.HM" treeStyle="TreeListSingle" layoutOrigin="2000,2000" layoutOrientation="BottomToTop" nodeDistance="1000" layerDistance="0"
        edgeType="Elbow" edgeTypeDesc="elbow:Target" >
    <edgemappingset name="TreeLS-CardinalPoints" />
  </tree>
  <tree name="ListS-Lo.LR-Pb.HM" treeStyle="TreeListSingle" layoutOrigin="2000,2000" layoutOrientation="LeftToRight" nodeDistance="1000" layerDistance="0"
